#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#
name: Eclipse Che operator image
on: [pull_request, push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build .
  buildx:
    name: Multi-platform build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: 5.2.0-1
    - name: Build images
      run: |
        docker buildx build \
        --platform linux/amd64,linux/ppc64le,linux/s390x \
        --output "type=image,push=false" \
        --tag quay.io/eclipse/che-operator:nightly \
        --file ./Dockerfile .
